extends: 'standard'
rules:
  'import/extensions': ['error', 'always', { ignorePackages: true }]
overrides:
  - files: ['*.ts', '*.tsx']
    extends: 'standard-with-typescript'
parserOptions:
  project: './tsconfig.json'
